package com.king.gmms.protocol.commonhttp.ws.vivas;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.sun.xml.internal.ws.client.BindingProviderProperties;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SendSMSService service = new SendSMSService();
 * SendSMSDelegate portType = service.getSendSMSPort();
 * portType.sendSMSAPI(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SendSMSService", targetNamespace = "http://ws.smsb.vivas.vn/", wsdlLocation = "http://123.30.23.179:8080/SMS_BN_Core_Server/SendSMSPort?wsdl")
public class SendSMSService extends Service {

	private final static URL SENDSMSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.king.gmms.protocol.commonhttp.ws.vivas.SendSMSService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.king.gmms.protocol.commonhttp.ws.vivas.SendSMSService.class.getResource(".");
			url = new URL(baseUrl,
					"http://123.30.23.179:8080/SMS_BN_Core_Server/SendSMSPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://123.30.23.179:8080/SMS_BN_Core_Server/SendSMSPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SENDSMSSERVICE_WSDL_LOCATION = url;
	}

	public SendSMSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SendSMSService() {
		super(SENDSMSSERVICE_WSDL_LOCATION, new QName(
				"http://ws.smsb.vivas.vn/", "SendSMSService"));
	}
	/**
	 * 
	 * @return returns SendSMSDelegate
	 */
	@WebEndpoint(name = "SendSMSPort")
	public SendSMSDelegate getSendSMSPort() {
		SendSMSDelegate smsDelegate = super.getPort(new QName("http://ws.smsb.vivas.vn/",
				"SendSMSPort"), SendSMSDelegate.class);
		((BindingProvider) smsDelegate).getRequestContext().put(
                BindingProviderProperties.REQUEST_TIMEOUT, 1000 * 60);
		((BindingProvider) smsDelegate).getRequestContext().put( "com.sun.xml.ws.request.timeout", 1000 *10 );//timeout
		((BindingProvider) smsDelegate).getRequestContext().put( "com.sun.xml.ws.connect.timeout", 1000 *10 );//timeout
		((BindingProvider) smsDelegate).getRequestContext().put( "com.sun.xml.internal.ws.connect.timeout", 1000 *10 );//timeout
		return smsDelegate;
	}

}
