package com.king.gmms.protocol.commonhttp.ws.vivas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SendSMSDelegate", targetNamespace = "http://ws.smsb.vivas.vn/")
public interface SendSMSDelegate {

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @param arg7
	 * @return returns vn.vivas.smsb.ws.ResponeObject
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendSMSAPI", targetNamespace = "http://ws.smsb.vivas.vn/", className = "vn.vivas.smsb.ws.SendSMSAPI")
	@ResponseWrapper(localName = "sendSMSAPIResponse", targetNamespace = "http://ws.smsb.vivas.vn/", className = "vn.vivas.smsb.ws.SendSMSAPIResponse")
	public ResponeObject sendSMSAPI(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4,
			@WebParam(name = "arg5", targetNamespace = "") String arg5,
			@WebParam(name = "arg6", targetNamespace = "") String arg6,
			@WebParam(name = "arg7", targetNamespace = "") MsgObjectRequest arg7);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns vn.vivas.smsb.ws.ResponeObject
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "verifySMSAPI", targetNamespace = "http://ws.smsb.vivas.vn/", className = "vn.vivas.smsb.ws.VerifySMSAPI")
	@ResponseWrapper(localName = "verifySMSAPIResponse", targetNamespace = "http://ws.smsb.vivas.vn/", className = "vn.vivas.smsb.ws.VerifySMSAPIResponse")
	public ResponeObject verifySMSAPI(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

}
